services:
  postgres:
    image: postgres:latest
    container_name: face-recognition-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 4CM13v1y
      POSTGRES_DB: face_recognition_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
